import type { Metadata } from "next";
import SubpageShell from "../SubpageShell";

export const metadata: Metadata = {
  title: "Música e musicalidade na dança | No Ritmo",
  description: "Aprenda a compreender a música para transformar sua escuta em movimento consciente na dança de salão.",
  alternates: { canonical: "/musicalidade" },
  openGraph: { title: "Música e musicalidade na dança | No Ritmo", description: "Um curso para aproximar música e movimento por meio de pulsação, frases, acentos, pausas e interpretação.", url: "/musicalidade", images: ["/logo-fundo-claro.png"] },
};

export default function MusicalidadePage() {
  return <SubpageShell wideCopy compactHero breadcrumbParent={{ label: "A No Ritmo", href: "/sobre" }} kicker="Música aplicada à dança" title="Compreender a música para dançar com ela." intro="Entre ouvir uma música e compreender o que ela está dizendo para o corpo existe um campo enorme de aprendizagem. É nesse espaço que entra nosso ensino de música aplicado à dança de salão." sections={[
    { number: "01", title: "O espaço entre ouvir e compreender", paragraphs: ["Na dança de salão, o aluno costuma ficar entre dois extremos: uma teoria musical excessivamente técnica ou a simples contagem de tempos. Aprendemos passos, figuras, condução, postura e técnica, mas ainda existe um campo enorme entre ouvir uma música e compreender o que ela está dizendo para o corpo.", <><strong>É exatamente nesse espaço que nós queremos entrar.</strong></>] },
    { number: "02", title: "Você não precisa se tornar músico para compreender música", paragraphs: ["O objetivo não é ensinar composição, partitura, contraponto ou uma análise harmônica aprofundada. Queremos selecionar o conhecimento musical que realmente ajuda quem dança e transformá-lo em percepção, escolha e movimento.", "A música será estudada a partir daquilo que pode ampliar a autonomia do dançarino dentro da sala de aula e do baile."] },
    { number: "03", title: "Antes de dançar, somos ouvintes", paragraphs: ["Vivemos cercados por música. Antes de aprender qualquer passo, nosso corpo já reage a sons, pulsos, pausas e mudanças de energia. Nossa primeira relação com a música acontece pela escuta.", "É como entrar em uma sala onde todos falam francês: mesmo sem compreender as palavras, percebemos o ritmo, as pausas, a intensidade e a intenção. Aprender música para dançar começa quando passamos a reconhecer essa linguagem."] },
    { number: "04", title: "Ouvir não é o mesmo que escutar", paragraphs: [<><strong>Ouvir</strong> é perceber o som.</>, <><strong>Escutar</strong> é direcionar a atenção.</>, <><strong>Compreender</strong> é reconhecer o que está acontecendo.</>, <><strong>Dançar</strong> é transformar essa compreensão em movimento.</>] },
    { number: "05", title: "O que um dançarino precisa aprender sobre música?", paragraphs: ["O dançarino pode aprender a reconhecer pulsação, tempo, contratempo, frase musical, acentos, pausas, dinâmica, repetição, mudanças de energia, intenção, estrutura e silêncio.", "Esses elementos não aparecem como uma lista distante da dança. Eles ajudam a perceber o que está acontecendo e a escolher como o corpo pode responder."] },
    { number: "06", title: "A contagem é uma ferramenta, não a música", paragraphs: ["Contar 1, 2, 3 ou organizar uma sequência ajuda na orientação temporal, especialmente no início da aprendizagem. Mas a contagem não esgota a experiência musical.", "A música contém muito mais informação do que uma sequência numérica: ela respira, cria expectativa, repousa, acelera, contrasta e muda de energia."] },
    { number: "07", title: "Da contagem para a intenção", paragraphs: ["No início, o aluno pode executar uma transferência de peso porque chegou determinado tempo. Com o desenvolvimento da escuta, passa a realizá-la porque percebe um acento, uma antecipação, uma resolução, uma pausa ou uma intenção musical.", "O movimento deixa de ser apenas uma resposta automática à contagem e passa a ser uma escolha consciente dentro da música."] },
    { number: "08", title: "Quando o corpo começa a responder à música", paragraphs: ["A compreensão musical influencia a pausa, a velocidade, a amplitude, a direção, a qualidade do movimento, a transferência de peso e a escolha de figuras.", "A dança se torna mais disponível para dialogar com o que acontece naquele momento, sem depender apenas de uma sequência previamente decorada."] },
    { number: "09", title: "Musicalidade não é decorar movimentos para uma música", paragraphs: ["Musicalidade não é apenas coreografia, repertório de passos ou a capacidade de repetir movimentos em uma música específica.", "Musicalidade é perceber acontecimentos musicais e tomar decisões corporais coerentes com eles, inclusive quando a música muda, quando a parceria muda ou quando a dança acontece de forma improvisada."] },
    { number: "10", title: "Sentir e compreender não são opostos", paragraphs: ["Estudar música não destrói a experiência emocional da dança. Pelo contrário: a linguagem pode ajudar o aluno a perceber conscientemente aquilo que antes apenas intuía.", "Compreender não significa deixar de sentir. Significa ampliar as possibilidades de atenção, interpretação e presença."] },
    { number: "11", title: "Aprender a escutar como dançarino", paragraphs: ["O objetivo não é fazer o aluno ouvir como compositor, instrumentista ou regente. É desenvolver uma forma de escuta orientada para o movimento e para a relação entre os corpos.", "É aprender a escutar com o corpo disponível, com atenção ao parceiro, ao espaço, à música e às possibilidades que surgem entre os três."] },
    { number: "12", title: "Dançar sobre a música ou dançar com a música?", paragraphs: ["Primeiro, o aluno executa movimentos enquanto a música toca. Depois, começa a organizar seus movimentos pelo tempo. Por fim, começa a tomar decisões corporais a partir do que escuta.", <><strong>Essa é a transformação: deixar de apenas dançar sobre a música para começar a dançar com a música.</strong></>] },
    { number: "manifesto", title: "Manifesto — Música na Dança de Salão", fullWidth: true, paragraphs: [<><strong>Não queremos formar músicos.</strong></>, <><strong>Queremos formar dançarinos capazes de perceber mais.</strong></>, "Pessoas que não apenas contem a música, mas reconheçam suas frases, seus acentos, suas pausas, seus contratempos, suas mudanças e suas intenções.", "Porque existe uma diferença entre executar um movimento enquanto uma música toca e permitir que aquilo que acontece na música participe da decisão do movimento.", <><strong>Nosso caminho passa por quatro etapas: ouvir, escutar, compreender e dançar.</strong></>], closing: "É nesse espaço que a No Ritmo quer ensinar música aplicada à dança de salão." },
  ]} ctaIntro="Música e movimento" ctaTitle="Descubra novas possibilidades de interpretar a dança de salão." />;
}
