import type { Metadata } from "next";
import SubpageShell from "../../SubpageShell";

export const metadata: Metadata = { title: "CFP — Curso de Formação Profissional em Dança de Salão | No Ritmo", description: "Conhecimento para dançar, método para ensinar e autonomia para continuar aprendendo.", alternates: { canonical: "/formacao/cfp" }, openGraph: { title: "CFP — Curso de Formação Profissional em Dança de Salão | No Ritmo", description: "Conhecimento para dançar, método para ensinar e autonomia para continuar aprendendo.", url: "/formacao/cfp", images: ["/logo-fundo-claro.png"] } };

export default function CfpPage() { return <SubpageShell compactHero wideCopy breadcrumbParent={{ label: "Serviços", href: "/servicos" }} kicker="Curso de formação" title="CFP — Curso de Formação Profissional em Dança de Salão" intro="Conhecimento para dançar, método para ensinar e autonomia para continuar aprendendo." sections={[
  { number: "01", title: "Saber dançar é uma coisa. Saber ensinar alguém a dançar é outra.", paragraphs: ["O CFP — Curso de Formação Profissional da No Ritmo é uma formação voltada para quem deseja compreender a dança de salão para além dos passos e desenvolver conhecimentos para atuar profissionalmente com o seu ensino.", <strong>Desde 2014, o CFP acontece nesses mesmos moldes na No Ritmo, integrando conhecimentos técnicos, pedagógicos e humanos à formação profissional em dança de salão.</strong>, "A proposta nasceu da percepção de que um bom professor não é necessariamente aquele que possui o maior repertório de movimentos, mas aquele que consegue transformar conhecimento em aprendizagem.", "Por isso, desde suas primeiras edições, o CFP reúne conhecimentos de diferentes áreas aplicados à dança de salão, abordando conteúdos como didática, andragogia, cinesiologia, comunicação verbal e não verbal, análise comportamental, musicalidade, universo rítmico, oratória, empreendedorismo e marketing pessoal, além do estudo técnico dos principais estilos de dança.", "Com o passar dos anos e a evolução da metodologia No Ritmo, a formação ganhou ainda mais profundidade.", "Hoje, o participante também é levado a compreender aspectos relacionados à fisiologia, percepção corporal, sistemas representacionais, canais perceptivos, escuta ativa, leitura de sala, comunicação, condução, segurança, prevenção de lesões e diferentes processos de ensino e aprendizagem."] },
  { number: "02", title: "Não ensinamos apenas o que fazer. Ensinamos a compreender.", paragraphs: ["Durante o CFP, cada conhecimento técnico é acompanhado de perguntas fundamentais: o que estou fazendo? Por que esse movimento funciona? Como posso explicá-lo? Como diferentes pessoas podem compreendê-lo? E como posso identificar se realmente houve aprendizagem?", "Essa forma de pensar transforma a relação do futuro professor com a dança.", "Em vez de simplesmente reproduzir aquilo que aprendeu, ele começa a desenvolver capacidade de observar, analisar, experimentar, adaptar e construir estratégias de ensino de acordo com as necessidades de cada aluno."], quote: "Se não houve aprendizagem, é porque não houve ensino." },
  { number: "03", title: "Aprender a aprender", paragraphs: ["Outro pilar fundamental do CFP é o desenvolvimento da autonomia.", "Acreditamos que uma formação profissional não deve criar professores dependentes de sequências prontas ou de um único método de explicação. Por isso, estimulamos aquilo que chamamos de “aprender a aprender”.", "O participante é incentivado a pesquisar, questionar, observar, testar, compreender fundamentos e construir conhecimento continuamente.", "Porque a formação de um professor não termina quando termina um curso."] },
  { number: "04", title: "Teoria que encontra a prática", paragraphs: ["O CFP aproxima o conhecimento teórico das situações reais encontradas dentro de uma sala de aula.", "O participante desenvolve sua capacidade de observar diferentes corpos, dificuldades, ritmos de aprendizagem e formas de comunicação, entendendo que pessoas diferentes podem precisar de caminhos diferentes para chegar ao mesmo aprendizado.", "Nesse processo, técnica e conhecimento caminham junto com comunicação, acolhimento, responsabilidade, liderança e desenvolvimento humano."] },
  { number: "05", title: "Uma formação para quem deseja ir além da dança", paragraphs: ["O CFP não foi criado apenas para formar pessoas que saibam demonstrar movimentos.", "Foi criado para desenvolver profissionais capazes de compreender a dança, compreender o aluno e compreender o processo que conecta os dois.", "Porque ensinar dança de salão envolve muito mais do que passos.", "Envolve pessoas."], closing: "CFP No Ritmo — Conhecimento para dançar. Método para ensinar. Autonomia para continuar aprendendo." },
]} />; }
