"use client";

import { useEffect, useState } from "react";

const testimonials = [
  ["Uma experiência maravilhosa e transformadora! Esta academia de dança de salão é simplesmente excepcional. Não apenas pelo profissionalismo e competência dos instrutores, mas também pela magia que ela traz para a alma. Ao entrar neste espaço, você é envolvido por uma atmosfera calorosa e acolhedora. Os instrutores não são apenas mestres em seus ofícios, mas também verdadeiros artistas que ensinam com paixão e paciência. Dançar aqui não é apenas aprender passos; é uma jornada para descobrir a beleza da dança, a conexão com o parceiro e a expressão da sua própria alma. Cada aula é uma terapia para a mente e o corpo, uma fuga do estresse diário. Recomendo esta academia a todos que desejam aprender dança de salão, independentemente do nível de habilidade. Além de ganhar confiança na pista de dança, você vai descobrir uma alegria profunda que vai muito além dos movimentos. É realmente um lugar maravilhoso que faz bem para a alma. Não perca a oportunidade de fazer parte desta incrível comunidade de dançarinos!", "Thaisa Vidal"],
  ["Sou aluno da No Ritmo Academia de Dança há 14 anos e minha experiência aqui tem sido simplesmente incrível! Durante todo esse tempo, não apenas aprendi diversas modalidades de dança, mas também tive a oportunidade de fazer muitos amigos que considero como uma família. Uma das maiores alegrias que tive foi aprender a dar aulas de dança, o que me trouxe uma realização enorme e me permitiu compartilhar meu amor pela dança com outros. Os professores são dedicados e apaixonados pelo que fazem, sempre motivando os alunos a se superarem e a desenvolverem seu potencial. A atmosfera da academia é acolhedora e estimulante, tornando cada aula uma experiência maravilhosa. Recomendo a No Ritmo para todos que desejam aprender a dançar, se divertir e fazer parte de uma comunidade vibrante e apaixonada pela dança!", "Luis Alan"],
  ["Quando entrei na academia estava precisando de algo para me distrair com a faculdade e problemas do dia a dia e foi a melhor escolha que fiz. Sou muito grata ao Luciano, a Helen e ao Leonardo por serem professores incríveis e com uma energia e paciência impossível de explicar. Fazer aula de dança na No Ritmo é uma experiência que qualquer pessoa deveria ter na vida e fiz amizades que quero levar para o resto da vida, sinto que são como uma verdadeira família. Além de aprender a dançar em tão pouco tempo, fazer aula na No Ritmo vai muito além disso, só quem vive e tem essa experiência sabe o quão incrível é a academia e as pessoas que frequentam. Perca a vergonha e o medo e tente fazer uma aula experimental, garanto que não vai se arrepender.", "Cyntia Natalia"],
  ["Realmente a Academia no Ritmo é diferenciada. E digo isso após conhecer muitas outras academias pelos lugares os quais passei. Embora \"se compre a aula de dança\", o produto oferecido vai muito além de apenas o aprender a dançar. A didática do professor é excepcional, o ambiente da academia é espetacular, os monitores estão preocupados com seu aprendizado e os alunos da academia são um tópico a parte em relação a simpatia e congraçamento. Para aqueles que sempre tiveram vontade de aprender e nunca tiveram a oportunidade ou mesmo coragem de se aventurar, tenham certeza que a Academia No Ritmo é o seu lugar. Você só irá se arrepender de não ter começado antes.", "Bruno Araujo"],
  ["Sempre tive vontade de dançar, mas nunca consegui aprender com ninguém. Até que conheci essa equipe fantástica, com profissionais maravilhosos, com uma didática incrível e sobre tudo, muito amor ao que estão fazendo. Hoje com poucos meses de aula, saindo do absoluto zero já consigo ver uma grande mudança, coisas que até então nunca me imaginei conseguir fazer, porém, por meio dos ensinamentos passados a mim já vejo uma enorme evolução, não só nos passos e movimentações, mas na confiança em mim mesmo! Um dos melhores investimentos que pude fazer por mim mesmo, que se resume a minha imensa gratidão por toda a equipe NoRitmo 💃🕺❤️", "Edson Corsini"],
  ["Conheci a academia através de uma postagem no Instagram e decidi começar porque sentia a necessidade de mudar minha rotina e encontrar algo que me distraísse. Essa escolha se revelou uma das melhores decisões que já tomei, pois, ao longo do último ano, a dança se tornou algo incrivelmente significativo em minha vida. Além de proporcionar a oportunidade de fazer novas amizades, a dança também me concedeu uma sensação de liberdade que jamais havia experimentado antes. Sinto uma profunda gratidão por todos os professores e indivíduos que fazem parte dessa jornada comigo. Agradeço muito à No Ritmo, pois ela realmente transformou minha vida para melhor.", "Enrico"],
  ["Tenho 41 anos e nunca tinha dançado, com um mês de aulas já estava me divertindo muito com essas pessoas maravilhosas, são minha família, os professores são muitos capacitados, nos passam segurança e nos ensinam muito facilmente, a melhor coisa que já fiz foi esse investimento, é uma terapia, uma nova fase da vida que só está melhorando cada vez mais, obrigado aos excelentes professores e a esse grupo maravilhoso que são minha família, hoje sou muito mais feliz graças a academia de dança NORITMO que está transformando a vida de centenas de pessoas nessa cidade. Pra quem quiser experimentar um novo jeito de viver a vida com qualidade eu desafio a qualquer pessoa a fazer uma aula experimental na academia de dança NORITMO, quem entra nunca mais sai.", "Marcio"],
  ["A experiência e o nível de aprendizado com o pessoal não tem preço e é inexplicável. Somente fazendo as aulas terão noção de como é ótimo. Auto estima se eleva e o ambiente com o pessoal é muito bom. Luciano e Helen muito atenciosos, pacientes e muito técnicos. As aulas são muito intuitivas e o nível de aprendizado é muito rápido e eficaz. Acredito que seja impossível não sair dançando mesmo que não saiba nenhum um passe de dança. Não dá vontade de ir embora! Super recomendo a todos! O local é divino, os problemas cotidianos somem e a felicidade prevalece! Dançar é viver!", "Alexsandro Szulek"],
  ["Foi uma experiência excelente! A menos de uma semana do nosso casamento procuramos o Luciano num domingo à noite e desde então ele começou a desenvolver a coreografia da nossa música. Foi uma semana desafiadora e de muita dedicação para que conseguíssemos fazer a nossa apresentação nesse dia tão importante das nossas vidas. Em resumo, o Luciano e a Helen salvaram a nossa valsa do casamento, pois por um momento achamos que não seria possível por conta do curto tempo que tínhamos naquela semana, mas com muita dedicação, quatro aulas por dia, aulas no feriado e algumas até passando da meia-noite, nossa apresentação aos convidados foi um sucesso, todos adoraram. Obrigado, Luciano e Helen!", "Acacio Lumikoski"],
  ["Estou muito satisfeito com as aulas particulares que tenho feito com a professora Lilian na Academia Dança No Ritmo. Ela é uma excelente instrutora, com um domínio incrível da técnica de dança. As aulas são sempre personalizadas e adaptadas às minhas necessidades, o que tem contribuído enormemente para meu progresso. Lilian tem uma forma única de ensinar, tornando o aprendizado leve e divertido, sem perder a seriedade na técnica. Sinto que estou evoluindo muito e me apaixonando ainda mais pela dança, graças ao seu método. Recomendo a todos que buscam aperfeiçoar suas habilidades na dança! Obrigado, professora Lilian.", "Wiliams Souza"],
];

export default function TestimonialRotator() {
  const [active, setActive] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setActive((current) => (current + 1) % testimonials.length), 12000); return () => window.clearInterval(timer); }, []);
  const previous = () => setActive((current) => (current - 1 + testimonials.length) % testimonials.length);
  const next = () => setActive((current) => (current + 1) % testimonials.length);
  return <div className="home-testimonial-rotator"><button className="testimonial-arrow testimonial-arrow-prev" type="button" onClick={previous} aria-label="Depoimento anterior">←</button><article key={active}><span>“</span><p>{testimonials[active][0]}</p><small>{testimonials[active][1]}</small></article><button className="testimonial-arrow testimonial-arrow-next" type="button" onClick={next} aria-label="Próximo depoimento">→</button><div className="testimonial-indicators" aria-label="Selecionar depoimento">{testimonials.map((_, index) => <button type="button" className={index === active ? "is-active" : ""} aria-label={`Mostrar depoimento ${index + 1}`} aria-pressed={index === active} onClick={() => setActive(index)} key={index}></button>)}</div></div>;
}
