import type { Metadata } from "next";
import SubpageShell from "../../SubpageShell";

export const metadata: Metadata = { title: "CFA — Curso de Formação de Assistentes | No Ritmo", description: "Muito além de aprender a dançar: compreenda o processo de ensinar e dê os primeiros passos no universo da formação.", alternates: { canonical: "/formacao/cfa" }, openGraph: { title: "CFA — Curso de Formação de Assistentes | No Ritmo", description: "Muito além de aprender a dançar: compreenda o processo de ensinar e dê os primeiros passos no universo da formação.", url: "/formacao/cfa", images: ["/logo-fundo-claro.png"] } };

export default function CfaPage() { return <SubpageShell compactHero wideCopy breadcrumbParent={{ label: "Serviços", href: "/servicos" }} kicker="Curso de formação" title="CFA — Curso de Formação de Assistentes" intro="Muito além de aprender a dançar: aprenda a compreender o processo de ensinar." sections={[
  { number: "01", title: "Muito além de aprender a dançar. Aprenda a compreender o processo de ensinar.", paragraphs: ["O CFA — Curso de Formação de Assistentes da No Ritmo foi desenvolvido para alunos que desejam aprofundar seus conhecimentos na dança de salão e dar os primeiros passos dentro do universo do ensino.", <strong>O CFA acontece desde 2010, ano em que a Academia No Ritmo nasceu. A formação de assistentes faz parte da história da escola desde o seu início.</strong>, "A proposta vai além de aprender novos passos e movimentações. Durante a formação, o participante começa a compreender como as pessoas aprendem, como observar uma turma, identificar dificuldades, comunicar uma orientação e colaborar com o professor durante uma aula.", "O curso integra conhecimentos técnicos da dança com temas fundamentais para a formação humana e pedagógica, como comunicação, escuta ativa, sistemas representacionais, fisiologia, percepção corporal, acolhimento, voluntariado, oratória e responsabilidade no processo de ensino-aprendizagem."] },
  { number: "02", title: "Um novo olhar sobre a dança", paragraphs: ["Na prática, o futuro assistente aprende a desenvolver um olhar diferente sobre a dança: deixa de observar apenas “o que fazer” e começa a compreender “como fazer, por que fazer e como ajudar outra pessoa a aprender”.", "Os participantes também têm contato com diferentes turmas e situações reais de aula, desenvolvendo progressivamente segurança, percepção e capacidade de interação com os alunos."] },
  { number: "03", title: "Uma oportunidade de crescimento", paragraphs: ["O CFA é, portanto, uma oportunidade de crescimento para quem deseja dançar melhor, comunicar-se melhor, desenvolver liderança e descobrir novas possibilidades dentro da dança de salão."], content: <p><strong>Você entra como aluno. Aprende a observar como assistente. E começa a enxergar a dança com os olhos de quem ensina.</strong></p> },
]} />; }
