import type { Metadata } from "next";
import SubpageShell from "../../SubpageShell";

export const metadata: Metadata = { title: "Dança de salão gratuita em Apucarana | No Ritmo", description: "Projeto de acesso gratuito à dança de salão em Apucarana, realizado com apoio da Prefeitura Municipal.", alternates: { canonical: "/projetos/danca-de-salao-gratuita-apucarana" }, openGraph: { title: "Dança de salão gratuita em Apucarana | No Ritmo", description: "Projeto de acesso gratuito à dança de salão em Apucarana, realizado com apoio da Prefeitura Municipal.", url: "/projetos/danca-de-salao-gratuita-apucarana", images: ["/logo-fundo-claro.png"] } };

export default function ProjetoDancaGratuitaPage() {
  return <SubpageShell breadcrumbParent={{ label: "Eventos e projetos", href: "/projetos" }} compactHero wideCopy kicker="Projeto gratuito" title="Dança de salão gratuita em Apucarana" intro="Uma oportunidade para aprender, conviver e se movimentar por meio da dança, com acesso gratuito à comunidade." sections={[
    { number: "01", title: "Sobre o projeto", text: "A Prefeitura de Apucarana oferece atividades culturais gratuitas por meio da Escola Municipal de Artes e de oficinas descentralizadas. Entre as ações estão cursos e oficinas de dança de salão, ampliando o acesso à formação artística e à convivência." },
    { number: "02", title: "O que você encontra", text: "As aulas apresentam ritmos variados da dança de salão e trabalham musicalidade, coordenação, conexão e expressão corporal em um ambiente acolhedor para diferentes idades e níveis de experiência." },
    { number: "03", title: "Onde e quando", content: <><p>Confira os locais e horários das aulas:</p><div className="schedule-table-wrap"><table className="schedule-table"><thead><tr><th>Dia</th><th>Local</th><th>Horário</th></tr></thead><tbody><tr><td data-label="Dia">Segunda-feira</td><td data-label="Local">Vila Reis</td><td data-label="Horário">7h às 9h</td></tr><tr><td data-label="Dia">Terça-feira</td><td data-label="Local">Igreja Nossa Senhora do Perpétuo Socorro — Jardim Trabalhista</td><td data-label="Horário">7h às 9h</td></tr><tr><td data-label="Dia">Quarta-feira</td><td data-label="Local">Vila Martins — Comunidade São Miguel Arcanjo</td><td data-label="Horário">18h15 às 20h15</td></tr><tr><td data-label="Dia">Quinta-feira</td><td data-label="Local">Academia No Ritmo</td><td data-label="Horário">14h às 16h</td></tr><tr><td data-label="Dia">Sexta-feira</td><td data-label="Local">Centro da Juventude — Jardim Diamantina</td><td data-label="Horário">7h às 9h</td></tr></tbody></table></div></> },
    { number: "04", title: "Como participar", text: "A participação é gratuita. Consulte a abertura de novas turmas, vagas e documentos necessários nos canais oficiais da Prefeitura de Apucarana antes de se deslocar." },
  ]} ctaIntro="Entre no Ritmo." ctaTitle="Participe das próximas turmas gratuitas e descubra a dança de salão em comunidade." />;
}
